### PR TITLE
Bump pyporscheconnectapi from 0.1.3 to 0.1.5

### PR DESCRIPTION
**Pull request by fredriklj**

### CODE REVIEW

**Comment by fredriklj** [comment]
Fixes #181

**Review by CJNE — CHANGES_REQUESTED** [review]
Thanks Fredrik!
We need to change the version number of the integration as well, to 0.0.16

**Comment by fredriklj** [comment]
Right, thought you might want to do that yourself in preparing the next release :-) Done now!

**Comment by tonycoupland** [comment]
This should also fix - at least the reported part of it - issue https://github.com/CJNE/ha-porscheconnect/issues/187 as well

**Comment by CJNE** [comment]
Sorry for the late action on this!

**Pull request merged**
