### PR TITLE
Direct charging services

### PR DESCRIPTION
**Pull request by fredriklj**
Services to request direct charging on/off

### CODE REVIEW

**Review by CJNE — COMMENTED** [review]
The VIN field should not be necessary, the  service should be either registered for an entity that belings to a specific device (car), or it should be device action instead:
https://developers.home-assistant.io/docs/device_automation_action
Either way, it should not be necessary to enter a VIN for this.

**Comment by fredriklj** [comment]
Looked at other similar integrations which seems to take the route with a service rather than a switch. I would imagine the latency of the backend messes up the status updates of a switch. 

The VIN here is optional, if you only have one vehicle it can be ignored. It was the only predictable selector I could come up with, and which I could test (as I only have one vehicle). But sure, I guess one could create a service per vehicle as well. Haven't seen other doing that before, doesn't mean it is wrong.

**Comment by fredriklj** [comment]
Giving this some more thought and testing, it should work to have both climate control and direct charging as switches, and create services to flash the parking light and sound the horn. In these cases I think it makes sense to use VIN as a selector, and this seems to be the way others have been doing it. Alongside the ability to provide device_id, which we could allow as well (but not very user friendly if you ask me – VIN is at least visible to the user). 

The latter have no feedback and no state, while both climate and direct charging state can be polled from the emobility endpoint (with a delay of a few seconds, as far as I can tell).

I will look into it when I get some more time.

**Comment by CJNE** [comment]
Climate control and direct charge are now availabel as switches and can be controlled by the UI or controlled using automations. 
I agree that parking light and horn should be services/device actions. 
If implemented as device actions there would be no need to enther a VIN since the device (car) will already have that information stored.

**Comment by fredriklj** [comment]
Excellent. Did find a bug and will file a new PR. Closing this.

**Pull request closed without merging**
